#example yaml for konovy
kind: ClusterProvisioner
apiVersion: konvoy.mesosphere.io/v1beta2
metadata:
  name: cks-dkp
  creationTimestamp: "2021-04-04T23:32:38Z"
spec:
  provider: aws
  aws:
    region: us-east-1
    vpc:
      overrideDefaultRouteTable: true
      enableInternetGateway: true
      enableVPCEndpoints: false
    availabilityZones:
      - us-east-1c
    elb:
      apiServerPort: 6443
    tags:
      owner: patricklogan
      expiration: 5d
  nodePools:
    - name: worker
      count: 1
      machine:
        imageID: ami-03eaf3b9c3367e75c
        rootVolumeSize: 80
        rootVolumeType: gp2
        imagefsVolumeEnabled: true
        imagefsVolumeSize: 160
        imagefsVolumeType: gp2
        imagefsVolumeDevice: xvdb
        type: m5.2xlarge
    - name: control-plane
      controlPlane: true
      count: 1
      machine:
        imageID: ami-03eaf3b9c3367e75c
        rootVolumeSize: 80
        rootVolumeType: io1
        rootVolumeIOPS: 1000
        imagefsVolumeEnabled: true
        imagefsVolumeSize: 160
        imagefsVolumeType: gp2
        imagefsVolumeDevice: xvdb
        type: m5.xlarge
    - name: bastion
      bastion: true
      count: 0
      machine:
        imageID: ami-03eaf3b9c3367e75c
        rootVolumeSize: 10
        rootVolumeType: gp2
        imagefsVolumeEnabled: false
        type: m5.large
  sshCredentials:
    user: ubuntu
    publicKeyFile: cks-dkp-ssh.pub
    privateKeyFile: cks-dkp-ssh.pem
  version: v1.7.0
---
kind: ClusterConfiguration
apiVersion: konvoy.mesosphere.io/v1beta2
metadata:
  name: cks-dkp
  creationTimestamp: "2021-04-04T23:32:38Z"
spec:
  kubernetes:
    version: 1.19.7
    networking:
      podSubnet: 192.168.0.0/16
      serviceSubnet: 10.0.0.0/18
      iptables:
        addDefaultRules: false
    cloudProvider:
      provider: aws
    admissionPlugins:
      enabled:
        - AlwaysPullImages
        - NodeRestriction
  containerNetworking:
    calico:
      version: v3.17.1
      encapsulation: ipip
      mtu: 1480
  containerRuntime:
    containerd:
      version: 1.3.9-1
      #ubuntu needs the -1 for the version
  osPackages:
    enableAdditionalRepositories: true
  nodePools:
    - name: worker
  addons:
    - configRepository: https://github.com/mesosphere/kubernetes-base-addons
      configVersion: stable-1.19-3.2.0
      addonsList:
        - name: ambassador # is currently in Experimental status. More information: https://docs.d2iq.com/dkp/konvoy/latest/version-policy/#experimental-status
          enabled: false
        - name: awsebscsiprovisioner
          enabled: true
        - name: awsebsprovisioner
          enabled: false
          values: |
            storageclass:
              isDefault: false
        - name: cert-manager
          enabled: false
        - name: dashboard
          enabled: false
        - name: defaultstorageclass-protection
          enabled: false
        - name: dex
          enabled: false
        - name: dex-k8s-authenticator
          enabled: false
        - name: elasticsearch
          enabled: false
        - name: elasticsearch-curator
          enabled: false
        - name: elasticsearchexporter
          enabled: false
        - name: external-dns
          enabled: false
        - name: flagger
          enabled: false
        - name: fluentbit
          enabled: false
        - name: gatekeeper
          enabled: false
        - name: istio # is currently in Experimental status. More information: https://docs.d2iq.com/dkp/konvoy/latest/version-policy/#experimental-status
          enabled: false
        - name: jaeger # is currently in Experimental status. More information: https://docs.d2iq.com/dkp/konvoy/latest/version-policy/#experimental-status
          enabled: false
        - name: kiali # is currently in Experimental status. More information: https://docs.d2iq.com/dkp/konvoy/latest/version-policy/#experimental-status
          enabled: false
        - name: kibana
          enabled: false
        - name: konvoyconfig
          enabled: false
        - name: kube-oidc-proxy
          enabled: false
        - name: localvolumeprovisioner
          enabled: false
          values: |
            # Multiple storage classes can be defined here. This allows to, e.g.,
            # distinguish between different disk types.
            # For each entry a storage class '$name' and
            # a host folder '/mnt/$dirName' will be created. Volumes mounted to this
            # folder are made available in the storage class.
            storageclasses:
              - name: localvolumeprovisioner
                dirName: disks
                isDefault: false
                reclaimPolicy: Delete
                volumeBindingMode: WaitForFirstConsumer
        - name: nvidia
          enabled: false
        - name: opsportal
          enabled: false
        - name: prometheus
          enabled: false
        - name: prometheusadapter
          enabled: false
        - name: reloader
          enabled: false
        - name: traefik
          enabled: false
        - name: traefik-forward-auth
          enabled: false
        - name: velero
          enabled: false
    - configRepository: https://github.com/mesosphere/kubeaddons-dispatch
      configVersion: stable-1.19-1.4.0
      addonsList:
        - name: dispatch
          enabled: false
    - configRepository: https://github.com/mesosphere/kubeaddons-kommander
      configVersion: stable-1.19-1.3.0
      addonsList:
       - name: kommander
         enabled: false
  version: v1.7.0
